### ISSUE TITLE
Discussion #1

### ISSUE THREAD

**Issue by Maetel1309** [Trololp/AVP2010MapViewer#1] opened 2021-07-04 17:09 UTC
[debug.txt](https://github.com/Trololp/AVP2010MapViewer/files/6760272/debug.txt)
I did follow all the steps that you provided but I encountered an issue to what appears to be memory problem (not sure if it is relying on GPU or system memory) and I feel like it should be optimized to use less memory if possible.
(Used AVP2010MapViewer release v0.5 - Ruins.pc / M04_Ruins.pc) (using a GT 1030 2gb and just 24GB of ram)

**Comment by Trololp** [comment] 2021-07-08 05:42
Unfortunately I can’t reproduce problem you have, because on my computers it works fine, you not the only one having this issue. If I did right things try this [fix](https://mega.nz/file/iZJ0WbQT#8ExGQQNL67LyXKKO2MeaLzZn25a074irfpyyD_bUGbY) 
If it not work for you can you probably download [AVP2010ModelViewer ](https://github.com/Trololp/AVP2010ModelViewer/releases/tag/v0.7) and check if it works, because it is mostly the same code.

**Comment by Maetel1309** [comment] 2021-07-10 14:59
[debug.txt](https://github.com/Trololp/AVP2010MapViewer/files/6795496/debug.txt)
Hmm... the fix did not help however instead of crashing instantly it was delayed for a somewhat 30 seconds while the screen was white at the time which I almost gave up (previously was able to see the map with the textures and everything but instant ctd) but then I decided to try out your model viewer and it did work for a specific file (M04_Ruins.pc, not Ruins.pc) but I also just realized the programs you made are just for viewing models, not for decompiling or exporting to a 3d format like a "Wavefront .obj file" (Edit: On second thought obj can't hold material data by itself so how about fbx?)

**Comment by Maetel1309** [comment] 2021-07-10 15:02
Now I'm starting to wonder if it's based on a specific game version or region/language that the program will work on or
It might be that some of the files are corrupted which I did check and it wasn't close to that.

**Comment by Trololp** [comment] 2021-07-11 08:59
Well it was kinda dumb, I forgot to add some files inside archive.  Also there were issues with Ruins M04, and A03, with entity loading... I hope now it will not crash and not stuck in infinity loop... Im sorry. Try this now [fix_test2](https://mega.nz/file/iAojBQjQ#E7RpPSchQncyvA9EVm_4uezMRCGzGwtGz-s_bEb9lQk).

**Comment by Maetel1309** [comment] 2021-07-12 13:33
[debug.txt](https://github.com/Trololp/AVP2010MapViewer/files/6801778/debug.txt)
I don't know what you did with the code but it works now and no more crashes, Loaded M04 Ruins successfully

**Comment by Maetel1309** [comment] 2021-07-12 17:52
But now that the problem is solved, is there any way to make all the objects exportable to 3d format along with it's materials? (it does not matter if it's not configured correctly, that can be fixed manually)
![Screenshot 2021-07-12 221237](https://user-images.githubusercontent.com/63059992/125379348-5d7f8000-e35e-11eb-9c9d-d381be95c411.png) I spent about 7 hours trying to align the position and fix unassigned materials (btw someone told me I could manually dump the map but that was complex as hell)

**Comment by Trololp** [comment] 2021-07-13 06:13
I forget to add this line after mapping constant buffer:
`g_pImmediateContext->Unmap(g_pConstantBuffer, 0);`
Simply on some video cards driver handles this correctly on other it seems to overflow memory.
It my first project with that size, before it was simple "hello world" programs :) code is pretty much looks like trash now.


For you question, do you read docs section ? There explanation of map format ([RSCF](https://github.com/Trololp/AVP2010MapViewer/blob/main/docs/Enviroment_RSCF.txt)), materials ([MARE](https://github.com/Trololp/AVP2010MapViewer/blob/main/docs/MARE.txt)), and others ?
Map consists of small meshes with only 1-2 material assigned to it, but that contain information of model it was imported from ("unk3" field I didn’t test it but I think this is imported mesh id) so it possible to dump out models somehow.
I can write same code in MapViewer as I did in ModelViewer but it dump all meshes in .obj format and still they need to be placed manually...

**Comment by Maetel1309** [comment] 2021-07-13 18:09
What you said "I can write same code in MapViewer as I did in ModelViewer but it dump all meshes in .obj format and still they need to be placed manually..." < I can work with placing it manually but what I really want is for it to have the textures assigned to the materials without having to do all of 1000+ meshes. As for your response with the docs, I did indeed read a little bit however I do not code or have experience with programming that much so yeah, ouch... (C++ is nightmare to me)

**Comment by Trololp** [comment] 2021-07-14 05:03
>  I really want is for it to have the textures assigned to the materials without having to do all of 1000+ meshes.

They all will be assigned to some materials. UV map will be saved. So basically it will be complete models as it is was inside game. 
One problem is that I don’t fully understand material format they use, so material will lost some properties (specularity, sharpness, etc.)


What about props? Do you need them to be dumped too?
Do you need a list of coordinates for objects inside map, and for prop location?
There 2 ways to do it (I can dump all meshes with saved position, but origin will be at 0,0,0 and this will be very bad for editing existing map, but easy to place (simply put all on 0,0,0 and map maybe will be complete, also I don't know how Unity work with models if you not watch at the center of model, it can disappear if you not watch at 0,0,0) or I can dump all meshes as it was independent model, and you must place every one on their spot, but it will be easy to modify map, and probably it is the best solution)
Pls, note that there is 300-1500 models map consists from.
Props can take about 900 models per map.

**Comment by Maetel1309** [comment] 2021-07-14 20:49
> One problem is that I don’t fully understand material format they use, so material will lost some properties (specularity, sharpness, etc.)

That's not really a problem, I can try to re-create the properties in unity by having a comparison with the game and unity.

> What about props? Do you need them to be dumped too?

Props? Not sure what you mean by that, if it's part of the map then yes, if not then no.

> Do you need a list of coordinates for objects inside map, and for prop location?

Not sure, might ask for it later.

> There 2 ways to do it (I can dump all meshes with saved position, but origin will be at 0,0,0 and this will be very bad for editing existing map, but easy to place (simply put all on 0,0,0 and map maybe will be complete, also I don't know how Unity work with models if you not watch at the center of model, it can disappear if you not watch at 0,0,0) or I can dump all meshes as it was independent model, and you must place every one on their spot, but it will be easy to modify map, and probably it is the best solution)

I would choose the first way of having their positions saved and having the origin at 0,0,0 but thank god unity has an option to render an object without having to look at the origin. (kind of a workaround but I can deal with it)

> Pls, note that there is 300-1500 models map consists from.

I understand the amount of models in the map, so it shouldn't be a big deal unless there's a problem.

> Props can take about 900 models per map.

Again, if it's part of the map then yes, if it is not then no (or you can have it as a togglable option)

**Comment by Trololp** [comment] 2021-07-17 07:12
So I worked for extracting models from the map.
There results
Blender:
![Blender_1](https://user-images.githubusercontent.com/71960487/126028775-2fbbc48f-b279-44dd-8f1f-5d102d4d4e9e.PNG)
Unity:
![Unity_test](https://user-images.githubusercontent.com/71960487/126028781-ca9e1eff-32ff-4852-b151-5ed54114a40b.PNG)

Pros:

>  I really want is for it to have the textures assigned to the materials without having to do all of 1000+ meshes.

-the most of textures are assigned automatically
-objects have meaningful names (as developers were set them)

Cons:

-Coordinates are flipped or mirrored
-Unity doesn't support normal_map + opacity map while importing .obj (maybe I'm wrong with it).
-I didn't test but I think if you add this to the game you need to add collision for it first. 
-Sometimes it crashes


There is console command `dump_map 1` for dumping with global coordinates (variant 1) or  `dump_map 2` if you need models without relative offset.
Ok there is my [build](https://mega.nz/file/7YpmzKgD#76fnJJ_OD4UUn_gl0ac62xnE1WG0Og2JGvf0bMkix_A)
It's buggy and can crash sometimes when map dumping happens.

Just curious how did you get map meshes for your unity project ?

**Comment by Maetel1309** [comment] 2021-07-18 00:02
> -the most of textures are assigned automatically
 
That's what I was worried about the most

> -Coordinates are flipped or mirrored

I actually encountered that issue and had to fix it manually one by one

> -Unity doesn't support normal_map + opacity map while importing .obj (maybe I'm wrong with it).

Maybe .obj wasn't the best format to use but at least it is simple than the .fbx format

> Just curious how did you get map meshes for your unity project ?

Asked a friend and they suggest using a software called ninja ripper which I ended up using it along with blender, noesis and unity. (and the way I did it was so complex/complicated)

**Comment by Maetel1309** [comment] 2021-07-18 00:04
![Screenshot 2021-07-17 194636](https://user-images.githubusercontent.com/63059992/126051899-7dfe40a8-c3cd-49cd-ab06-a8aeab538c40.png)
![Screenshot 2021-07-17 200244](https://user-images.githubusercontent.com/63059992/126051901-f5c12ca3-0c64-4da8-9b33-f82b0ff03ef9.png)

This literally took me about 3 days assigning textures, fixing coordinates and don't know rest of the issues.

**Comment by Trololp** [comment] 2021-07-18 04:10
Using ninja ripper? So you ended up with a bunch of no-name models, and no materials, no UV-map. For me, it sounds like you building a gigantic 3d puzzle that has no colors while you are being blind. If I started doing something like this I will eventually giving up in about 3 hours.

**Comment by Maetel1309** [comment] 2021-07-19 21:52
> Using ninja ripper? So you ended up with a bunch of no-name models, and no materials, no UV-map. For me, it sounds like you building a gigantic 3d puzzle that has no colors while you are being blind. If I started doing something like this I will eventually giving up in about 3 hours. 

But I didn't give up and it was a rushed idea so...

**Comment by Maetel1309** [comment] 2021-07-20 03:38
> There is console command `dump_map 1` for dumping with global coordinates (variant 1) or `dump_map 2` if you need models without relative offset.

I'm not sure if I'm doing the command right but nothing is happening once I enter it, any solution or am I doing something wrong?

**Comment by Trololp** [comment] 2021-07-20 10:29
I don't know. Are you write it as "dump_map 1" or "dump_map 2" ? If you simply write
"dump_map" won't be working.

**Comment by Maetel1309** [comment] 2021-07-20 14:14
> I don't know. Are you write it as "dump_map 1" or "dump_map 2" ? If you simply write
> "dump_map" won't be working.

Sorry for wasting your time, I had found a broken key in my pc ( which was the _ )and using a fixed one was the solution

**Comment by Maetel1309** [comment] 2021-07-20 17:08
Have you figured out why some materials are not assigned (not the pink/purple ones or checkerboard) such as the white parts
![Screenshot 2021-07-20 130617](https://user-images.githubusercontent.com/63059992/126366233-a2a820f7-964f-406b-84f7-5232bdce5c10.png)

**Comment by Trololp** [comment] 2021-07-21 05:50
It seems that Unity doesn't support some textures this game uses,
`Could not create asset from Assets/test/Materials/material_105e740b/ms_pump_room_c_transparent.tga: File could not be read`
so when it sees broken material inside some objects he decides to go and do some things, I'm not a Unity developer idk what it does, but I imported it with blender and the textures were ok. so my opinion it is a Unity problem.

**Comment by Maetel1309** [comment] 2021-07-24 01:35
Kind of regret having the whole map dumped as a mirrored mesh but I decided to give up half way and think about another idea.

**Comment by Maetel1309** [comment] 2021-07-24 01:37
Why not reverse engineer how the game works online and figure out how to make it work without steam and use a custom server (like avp2 I believe)

**Comment by Trololp** [comment] 2021-07-24 13:57
That sounds like a good idea!
[Some intro to reverse engineering](https://www.youtube.com/watch?v=VroEiMOJPm8)
I am using an IDA disassembler.
You can use my IDA database, this can be your starting point, [link](https://mega.nz/file/nJwFVCaJ#SVwJPzHRaglp5UzWM2kEO6IMANUerLUkDsvr3nJfUkc)

**Comment by Maetel1309** [comment] 2021-07-25 20:58
> You can use my IDA database, this can be your starting point, [link](https://mega.nz/file/nJwFVCaJ#SVwJPzHRaglp5UzWM2kEO6IMANUerLUkDsvr3nJfUkc)

Not really a programmer or engineer but it is very interesting that you have made such progress on database for debugging and other stuff.

**Comment by Maetel1309** [comment] 2021-07-27 07:54
This is just a request<(meaning you can or deny it) but could you patch my dx11 exe of avp to have the console unlocked because the one that you provided on your YouTube video does not work, throws a corrupt error.
[AvP_DX11.zip](https://github.com/Trololp/AVP2010MapViewer/files/6883708/AvP_DX11.zip)

**Comment by Trololp** [comment] 2021-07-28 09:26
![Безымянный](https://user-images.githubusercontent.com/71960487/127295835-99ddfd46-fc9b-499a-b0c5-2d6355288f45.png)
they are different files. but ok that [not hard (probably)](https://mega.nz/file/CZRlmSaQ#cuPOFtZmgHdnettfQIl8LetVN5q-v621xSw5UM-zXyw)

**Comment by Maetel1309** [comment] 2021-07-28 16:47
> they are different files. but ok that [not hard (probably)

Scratch it might actually be that hard
![Screenshot 2021-07-28 124512](https://user-images.githubusercontent.com/63059992/127363180-babba37d-e335-4de3-90bf-fce753f1efd9.png)

Is there any file that you need required/location?

**Comment by Trololp** [comment] 2021-07-29 05:19
![image](https://user-images.githubusercontent.com/71960487/127435553-520f7648-214e-45f2-9f05-d79770f26bfb.png)
That is strange. On my computer it works fine.
This error can refer to missing dlls or something.
Use this [tool](https://docs.microsoft.com/ru-ru/sysinternals/downloads/procmon) to see what your application missing.

**Comment by Maetel1309** [comment] 2021-08-05 06:15
I think patching the console won't be easy because the steam version is a bit different than the normal cd rom release. (but I also gave up since I couldn't find a trace on why the error pops up)

**Comment by Trololp** [comment] 2021-08-05 06:25
I patched your .exe, it works fine for me (I launched it and it works fine, with no errors) so I dont know what is your problem.

**Comment by Maetel1309** [comment] 2021-08-05 21:37
Okay, there's one .dll missing which is Steamclient.dll which I do not have and getting would be difficult since there are different versions for different games so... could you provide with yours?

**Comment by Trololp** [comment] 2021-08-06 06:19
[.](https://mega.nz/file/WVwWHJjR#UgSBL2fi5bnm5gmMj6ULYYlzqe-eH3683cfyADEpRXw)

**Comment by Maetel1309** [comment] 2021-08-08 03:23
> > they are different files. but ok that [not hard (probably)
> 
> Scratch it might actually be that hard
> ![Screenshot 2021-07-28 124512](https://user-images.githubusercontent.com/63059992/127363180-babba37d-e335-4de3-90bf-fce753f1efd9.png)
> 
> Is there any file that you need required/location?

 I did not get this error but
Apparently, it happens when there is no app id found/configured or steamclient .dll and I also found someone else complaining for a mod of a different game but no solution (9 years ago).

**Comment by Maetel1309** [comment] 2021-08-08 03:23
![Screenshot 2021-08-07 231943](https://user-images.githubusercontent.com/63059992/128619678-1ccc368d-2fea-4a24-8231-a382110a35fc.png)

**Comment by Maetel1309** [comment] 2021-08-08 03:45
You know what... I got a better solution lets do it in the demo version, Things will be different for that version but at least everyone can download it if they know what they are doing with depots.

**Comment by Trololp** [comment] 2021-08-08 06:13
Can you do it yourself? I think you are very persistent in that questions, you will find a solution for your problem. Also please notice that demo version is indeed "DEMO VERSION", you will not play game normally as if it was released. You can't even run singleplayer level from menu.

**Comment by Maetel1309** [comment] 2021-08-08 22:54
> Can you do it yourself? I think you are very persistent in that questions, you will find a solution for your problem. Also please notice that demo version is indeed "DEMO VERSION", you will not play game normally as if it was released. You can't even run singleplayer level from menu.

You are right, I am very persistent and overthinking it too much that I'm completely sorry for making you do all of this

**Comment by Maetel1309** [comment] 2021-08-25 15:11
It's been a while since I've last spoken and I have successfully ported the map with their textures fixed along with them being unmirrored but could I request you find a solution from preventing it from crashing by dumping a specific map? (maybe it's executing too fast?)

**Comment by Trololp** [comment] 2021-08-26 04:14
witch map it struggles to dump? Also, can you tell in what direction models are mirrored, or it is textures mirrored?

**Comment by Maetel1309** [comment] 2021-08-26 15:36
If my memory is correct, it was the predator pyramid map that was having problems only to have the predalien boss room dumped on crash and also don't worry about the mirrored problem, textures were fine.

**Comment by Trololp** [comment] 2021-08-27 07:52
```
line 862 on Load_map.cpp
before:
if (mmi_part_id < t_m)
after:
if (mmi_part_id < t_m - 1)
```
Imagine adding 2 characters and solve the problem. But ok, I published a new realize, you can download it normally without these strange sites.
Also, I solved mirroring.

**Comment by Maetel1309** [comment] 2021-08-29 01:10
As I said earlier, I'm not a programmer but I cannot figure out why I cannot open up the predator tutorial map at all? (P00_Tutorial.pc, P00_PredTutorial) I'm very curious what's actually out behind the scenes,

Edit 2: Maybe I should actually test all the maps and see if they don't break and I don't waste your time so much for one thing at a time.

**Comment by Maetel1309** [comment] 2021-08-29 01:54
Actually scratch that, MP Jungle is the same as the predator tutorial so no work for you to do.

**Comment by Trololp** [comment] 2021-08-29 08:32
- P00_Tutorial.pc (this is map)
- P00_PredTutorial.pc (this is entities)
for MP
- MP_CBlock.pc (this is map)
- MP_00_CBlock.pc (this is entities)
Just unpack those files and select folders in order.
I can open Predator Tutorial map.
I tried open MP map and it's work for me.

You can check if you unpacked correctly:
Folder with map should have file named "Env.RSCF"

**Comment by Maetel1309** [comment] 2021-09-05 03:29
Could you remove the mirror fix but keep the crash fix because apparently the textures are not facing the right direction.
![Screenshot 2021-09-04 232119](https://user-images.githubusercontent.com/63059992/132113935-a5f5a547-0717-4334-887f-e958d63fc4be.png)
Edit 1: I've already found a solution earlier to this which is by turning culling off but that's also causing issues with how the lighting and normals work.

**Comment by Trololp** [comment] 2021-09-05 05:20
That's. bad. sorry. Test [this](https://mega.nz/file/HBIkQZ5Q#buk7hYmGoljIEhgjLiVd0taoxsiaBWD1p-RiGcUTYXw).

**Comment by Maetel1309** [comment] 2021-09-06 06:20
Still no difference (using Jungle.pc)
Edit 1: Previously on a older version of the map viewer, the direction of models are mirrored and it was very easy to fix it but apparently you also fixed it which also caused that other problem.

**Comment by Trololp** [comment] 2021-09-08 05:47
So I downloaded it from a link I have given to you. Extracted it into a new folder. Loaded (Jungle.pc), pressed 'P', then I write "dump_map 1", then wait for some time, Then I started unity (version 2020.3.4f1), and then I imported that folder with all stuff. waited for about 5 minutes. And then put meshes into the map. I am not an expert on Unity, I never made a game on it, can you explain why is my meshes look fine?
![Tree_top](https://user-images.githubusercontent.com/71960487/132451488-b823d520-1c2a-4ed8-8d16-6d618399cab4.PNG)
![img1](https://user-images.githubusercontent.com/71960487/132451494-dfc0d8b8-d851-4576-b9bf-7ba43ef21627.PNG)
![img2](https://user-images.githubusercontent.com/71960487/132451500-b34aa286-c8c8-405e-8a6b-9cad695b6cef.PNG)
![img3](https://user-images.githubusercontent.com/71960487/132451505-e00bf2b4-6ef4-4dbd-ad73-3dbfd44ea26d.PNG)
This is comparasion between mirror fix and no mirror fix: wall with "(1)" in name is no mirror fix version.
![image](https://user-images.githubusercontent.com/71960487/132452669-133bfa0f-e998-4e80-9142-21cd6ec4c1ad.png)

[Version with no mirror fix](https://mega.nz/file/vRowCIBC#nNhUNE868e3QQin_f5vcy14vqQbekA8YNATNIP0K0rI)

**Comment by Maetel1309** [comment] 2021-09-09 00:49
Using Unity version 2019.4.28f1 but I did actually broke my unity project so it is my fault, so sorry

**Comment by Trololp** [comment] 2021-09-09 07:30
No problem, without your help I didnt notice that triangles was flipped.

**Comment by Maetel1309** [comment] 2021-09-10 23:12
is there by any chance a faster way to contact you instead using github (an example could be discord, skype, etc)

**Comment by Trololp** [comment] 2021-09-11 12:26
Yes, sure. trololp#8360 discord

**Closed as completed** 2022-11-20 06:01 UTC
